version: '3.9'

services:
  web:
    build: .
    container_name: weight_scraper
    volumes:
      - ./src:/app/src
    environment:
      - FLASK_ENV=development
    restart: unless-stopped
    command: tail -f /dev/null