version: '3.9'

services:
  weight_app:
    build:
      context: .
      dockerfile: weight_app/Dockerfile
    container_name: weight_app
    ports:
      - "80:5000"
    volumes:
      - ./weight_app/src:/app/src
    environment:
      - LOSEIT_EMAIL=${LOSEIT_EMAIL}
      - LOSEIT_PASSWORD=${LOSEIT_PASSWORD}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - HEIGHT=${HEIGHT}
      - DOB=${DOB}
      - AGE=${AGE}
      - HEAVY_WEIGHT=${HEAVY_WEIGHT}
      - CRON_TIME=${CRON_TIME}
      - DOWNLOAD_PATH=${DOWNLOAD_PATH}
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy

  scrape_app:
    build:
      context: .
      dockerfile: scrape_app/Dockerfile
    container_name: scrape_app
    environment:
      - LOSEIT_EMAIL=${LOSEIT_EMAIL}
      - LOSEIT_PASSWORD=${LOSEIT_PASSWORD}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - HEIGHT=${HEIGHT}
      - DOB=${DOB}
      - AGE=${AGE}
      - HEAVY_WEIGHT=${HEAVY_WEIGHT}
      - CRON_TIME=${CRON_TIME}
      - DOWNLOAD_PATH=${DOWNLOAD_PATH}
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}        # Change this
      MYSQL_DATABASE: ${DB_NAME}              # Optional: initial database
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_database:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysql -u${DB_USERNAME} -p${DB_PASSWORD} -e 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 10