version: '3.9'

services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "80:5000"
    volumes:
      - ./src:/app/src
    environment:
      - FLASK_ENV=development
    restart: unless-stopped
